#!/usr/bin/env python3
"""
Document Ingestion — chunks files and stores them in a local ChromaDB vector store
with embeddings generated by Ollama.

Supported file types: .md, .txt, .py, .cpp, .h, .js, .ts, .json, .pdf (optional)

Usage:
    python -m rag.ingest --config config.json --source docs/ specs/
    python -m rag.ingest --config config.json --source README.md
    python -m rag.ingest --config config.json --clear  # Reset the collection
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Optional

# Text file extensions supported out of the box
TEXT_EXTENSIONS = {".md", ".txt", ".py", ".cpp", ".h", ".c", ".hpp",
                   ".js", ".ts", ".jsx", ".tsx", ".json", ".yaml", ".yml",
                   ".toml", ".cfg", ".ini", ".sh", ".bat", ".ps1", ".html", ".css"}


def load_config(config_path: Optional[str] = None) -> dict:
    path = Path(config_path) if config_path else Path.cwd() / "config.json"
    if path.exists():
        with open(path) as f:
            return json.load(f)
    return {}


def chunk_text(text: str, chunk_size: int = 512, overlap: int = 50) -> list[str]:
    """Split text into overlapping chunks by character count."""
    if len(text) <= chunk_size:
        return [text] if text.strip() else []
    chunks = []
    start = 0
    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end]
        if chunk.strip():
            chunks.append(chunk)
        start = end - overlap
    return chunks


def read_file(path: Path) -> Optional[str]:
    """Read a file's text content. Returns None for unsupported types."""
    if path.suffix == ".pdf":
        try:
            import fitz  # PyMuPDF
            doc = fitz.open(str(path))
            text = "\n".join(page.get_text() for page in doc)
            doc.close()
            return text
        except ImportError:
            print(f"  Skipping PDF {path.name} (install PyMuPDF: pip install PyMuPDF)")
            return None
    elif path.suffix in TEXT_EXTENSIONS:
        try:
            return path.read_text(encoding="utf-8", errors="replace")
        except Exception as e:
            print(f"  Error reading {path}: {e}")
            return None
    return None


def collect_files(sources: list[str]) -> list[Path]:
    """Collect all ingestible files from source paths (files or directories)."""
    all_extensions = TEXT_EXTENSIONS | {".pdf"}
    files = []
    for src in sources:
        p = Path(src)
        if p.is_file() and p.suffix in all_extensions:
            files.append(p)
        elif p.is_dir():
            for ext in all_extensions:
                files.extend(p.rglob(f"*{ext}"))
    return sorted(set(files))


def ingest(config: dict, sources: list[str], clear: bool = False) -> int:
    """Ingest documents into ChromaDB. Returns count of chunks stored."""
    try:
        import chromadb
    except ImportError:
        print("ERROR: chromadb not installed. Run: pip install chromadb")
        sys.exit(1)

    from rag.embeddings import OllamaEmbeddingFunction

    rag_cfg = config.get("rag", {})
    persist_dir = rag_cfg.get("persist_directory", ".rag_store")
    collection_name = rag_cfg.get("collection_name", "domain_knowledge")
    embedding_model = rag_cfg.get("embedding_model", "nomic-embed-text")
    ollama_url = config.get("model_proxy", {}).get("local", {}).get("base_url", "http://localhost:11434")
    chunk_size = rag_cfg.get("chunk_size", 512)
    chunk_overlap = rag_cfg.get("chunk_overlap", 50)

    # Initialize ChromaDB with Ollama embeddings
    embed_fn = OllamaEmbeddingFunction(model=embedding_model, base_url=ollama_url)
    client = chromadb.PersistentClient(path=str(Path(persist_dir).resolve()))

    if clear:
        try:
            client.delete_collection(collection_name)
            print(f"Cleared collection: {collection_name}")
        except Exception:
            pass

    collection = client.get_or_create_collection(
        name=collection_name,
        embedding_function=embed_fn,
    )

    # Collect and process files
    files = collect_files(sources)
    if not files:
        print("No files found to ingest.")
        return 0

    print(f"\nIngesting {len(files)} files into '{collection_name}'...")
    total_chunks = 0

    for filepath in files:
        text = read_file(filepath)
        if not text:
            continue
        chunks = chunk_text(text, chunk_size, chunk_overlap)
        if not chunks:
            continue

        # Generate IDs and metadata
        ids = [f"{filepath.name}:chunk:{i}" for i in range(len(chunks))]
        metadatas = [{"source": str(filepath), "chunk_index": i, "total_chunks": len(chunks)}
                     for i in range(len(chunks))]

        # Upsert (idempotent — re-running updates existing chunks)
        collection.upsert(ids=ids, documents=chunks, metadatas=metadatas)
        total_chunks += len(chunks)
        print(f"  + {filepath.name}: {len(chunks)} chunks")

    print(f"\nDone. {total_chunks} chunks stored in {persist_dir}/")
    print(f"Collection '{collection_name}' now has {collection.count()} total documents.")
    return total_chunks


def main():
    parser = argparse.ArgumentParser(description="Ingest documents into RAG vector store")
    parser.add_argument("--config", help="Path to config.json")
    parser.add_argument("--source", nargs="+", required=True, help="Files or directories to ingest")
    parser.add_argument("--clear", action="store_true", help="Clear the collection before ingesting")
    args = parser.parse_args()

    config = load_config(args.config)
    ingest(config, args.source, args.clear)


if __name__ == "__main__":
    main()
